### ISSUE TITLE
setup on mac

### ISSUE THREAD

**Issue by am01** [Nanoseb/ncTelegram#21]
Is it possible to install nctelegram on OSX?
All attempts failing with 'ncTelegram' module not found, same for setup.py.
Thanks

**Comment by prafiles** [comment]
I had the same issue. Its because the binary has the same name as the folder, and HFS+ on default settings overwrites the file/directory with the other.

**Comment by Nanoseb** [comment]
Yes exactly, HFS+ is not case sensitive, see #9, you can manually rename the script name to something else if you want.
