### ISSUE TITLE
telegram-cli error

### ISSUE THREAD

**Issue by xeyalxx** [Nanoseb/ncTelegram#26]
Hi. I try to install `nctelegram-git` on Arch and `yaourt` write `error: target not found: telegram-cli`. And when I try to install `telegram-cli` `yaourt` write same. `telegram-cli-git` established normally, but `nctelegram-git` not install :(

**Comment by Nanoseb** [comment]
It should be fixed now. Even if this was an error of yaourt (the web interface shows the right dependencies).
