### ISSUE TITLE
Remote end Close

### ISSUE THREAD

**Issue by nautilor** [Nanoseb/ncTelegram#30]
`$ Traceback (most recent call last):`
`  File "/usr/bin/nctelegram", line 93, in <module>`
`Exception in thread Receiver (pytg):`
`Traceback (most recent call last):`
`  File "/usr/lib/python3.6/threading.py", line 916, in _bootstrap_inner`
`    self.run()`
`  File "/usr/lib/python3.6/threading.py", line 864, in run`
`    self._target(*self._args, **self._kwargs)`
`  File "/usr/lib/python3.6/site-packages/pytg/receiver.py", line 125, in _receiver`
`    raise ConnectionError("Remote end closed.")`
`pytg.exceptions.ConnectionError: Remote end closed.`
`    ncTelegram.Telegram_ui(config_full)`

`  File "/usr/lib/python3.6/site-packages/ncTelegram/__init__.py", line 73, in __init__`
`    self.msg_widget = MessageWidget(self)`
`  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 25, in __init__`
`    self.get_history()`
`  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 60, in get_history`
`    self.print_msg(msg)`
`  File "/usr/lib/python3.6/site-packages/ncTelegram/ui_msgwidget.py", line 141, in print_msg`
`    msg_reply = self.Telegram_ui.sender.message_get(msg['reply_id'])`
`  File "/usr/lib/python3.6/site-packages/pytg/sender.py", line 630, in command_alias`
`    return self.execute_function(command_name, *args, **kwargs)`
`  File "/usr/lib/python3.6/site-packages/pytg/sender.py", line 320, in execute_function`
`    result = self._do_send(request, answer_timeout=self.default_answer_timeout,` `retry_connect=retry_connect)`
`  File "/usr/lib/python3.6/site-packages/pytg/sender.py", line 507, in _do_send`
`    raise ConnectionError("Remote end closed")`
`pytg.exceptions.ConnectionError: Remote end closed`

this is what happen even if I leave it open doing nothing

**Comment by skvoter** [comment]
+

**Comment by bandithijo** [comment]
have the same issue too
