### ISSUE TITLE
Kill all instances of telegram-cli on load.

### ISSUE THREAD

**Issue by wildefyr** [Nanoseb/ncTelegram#7]
Just an idea for now at least in early development to ensure the user isn't open a billion telegram-cli's if nctelegram isn't closing it properly.

**Comment by Nanoseb** [comment]
Something a little more clever that is also quite easy to implement is to check if the port I am using (4588) is available or not (and that makes more sense since telegram-cli can be opened for something else without interfering).

**Comment by wildefyr** [comment]
+1
