### ISSUE TITLE
Using it on OSX

### ISSUE THREAD

**Issue by FerranCelades** [Nanoseb/ncTelegram#9]
Its possible to use it on OSX?. Im having problems.

**Comment by Nanoseb** [comment]
I don't know, probably, but if you don't explain the issue I can't help you.

**Comment by FerranCelades** [comment]
I have solved it. The problem was unziping the release version, asking me to replace a file. So i renamed the problematic file.
```
/Users/*/Downloads/ncTelegram-0.9.6.zip
  creating: ncTelegram-0.9.6/
  inflating: ncTelegram-0.9.6/.gitignore
  inflating: ncTelegram-0.9.6/LICENSE
  inflating: ncTelegram-0.9.6/README.md
  inflating: ncTelegram-0.9.6/ncTelegram.conf
   creating: ncTelegram-0.9.6/ncTelegram/
  inflating: ncTelegram-0.9.6/ncTelegram/__init__.py
  inflating: ncTelegram-0.9.6/ncTelegram/msg_receiver.py
  inflating: ncTelegram-0.9.6/ncTelegram/ui_chanwidget.py
  inflating: ncTelegram-0.9.6/ncTelegram/ui_msgsendwidget.py
  inflating: ncTelegram-0.9.6/ncTelegram/ui_msgwidget.py
  inflating: ncTelegram-0.9.6/ncTelegram/ui_popup.py
replace ncTelegram-0.9.6/nctelegram? [y]es, [n]o, [A]ll, [N]one, [r]ename: r
new name: ncTegram-0.9.6/nc_telegram
  inflating: ncTegram-0.9.6/nc_telegram
  inflating: ncTelegram-0.9.6/setup.py
  inflating: ncTelegram-0.9.6/t_logo.png
```
Then changed in setup.py this line:
>       scripts=['nc_telegram']

Finally, I installed it with pip3 and seams to work fine.

**Comment by Nanoseb** [comment]
Ok that's weird file name are not case sensitive on osx ?
and why didn't you install it directly with ```pip3 install --upgrade https://github.com/Nanoseb/ncTelegram/archive/master.tar.gz``` ?

**Comment by FerranCelades** [comment]
Yes, they are case sensitive but don't let me unzip it anyway. I tried the direct pip install and i got the same problem but with tmp files.

```
IsADirectoryError: [Errno 21] Is a directory: '/var/folders/mv/wkcszm4x5rd2f3hgsztbphwh0000gn/T/pip-vw3mqlij-build/nctelegram'
```

**Comment by Nanoseb** [comment]
Ok so the problem is that HPFS and HFS+ are not case sensitive (https://en.wikipedia.org/wiki/Comparison_of_file_systems#Features)...
